name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: LizAinslie/VueBuildToBranchAction@1.0.2
      with:
        username: 'cainbryce208'
        reponame: 'Rxt-Tournaments'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        gitbranch: 'deployment' # defaults to 'gh-pages' but can be changed
