name: Build Deployment
  on: [push]
  jobs:
    checkout_web:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
    build_web:
      runs-on: ubuntu-latest
      - name: Build
      run: |
            cd Rxt-Tournaments
            npm run build
    push_web:
      runs-on: ubuntu-latest
      name: Push To Web
      runs:
        steps:
        -name: Push to Branch
        run: |
              cd dist
              git config --global user.email "${{ BRYCE_EMAIL }}"
              git config --global user.name "${{ BRYCE_USERNAME }}"
              git init
              git add -A
              git commit -m "Deployment"
              git push -f https://${{ BRYCE_EMAIL }}:${{ BRYCE_PAC }}@github.com/${{ BRYCE_USERNAME }}/Rxt-Tournaments.git origin deployment
        shell: bash
